-- ============================================================
-- import.sql
-- ddl-auto=create 로 서버 기동 시 자동 실행됨
-- SQL 데이터 INSERT 완료 후 시퀀스를 최댓값으로 맞춰주는 스크립트
-- ============================================================

-- ── VOTE_SEQ (최대 vote_id: 30740) ──────────────────────────
ALTER SEQUENCE VOTE_SEQ INCREMENT BY 30740 NOCACHE;
SELECT VOTE_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE VOTE_SEQ INCREMENT BY 1 NOCACHE;

-- ── VOTE_DETAIL_SEQ (최대 vote_detail_id: 153792) ────────────
ALTER SEQUENCE VOTE_DETAIL_SEQ INCREMENT BY 153792 NOCACHE;
SELECT VOTE_DETAIL_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE VOTE_DETAIL_SEQ INCREMENT BY 1 NOCACHE;

-- ── IDOL_SEQ (최대 idol_id: 215) ─────────────────────────────
ALTER SEQUENCE IDOL_SEQ INCREMENT BY 215 NOCACHE;
SELECT IDOL_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE IDOL_SEQ INCREMENT BY 1 NOCACHE;

-- ── VOTE_BONUS_SEQ (최대 bonus_id: 50) ───────────────────────
ALTER SEQUENCE VOTE_BONUS_SEQ INCREMENT BY 50 NOCACHE;
SELECT VOTE_BONUS_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE VOTE_BONUS_SEQ INCREMENT BY 1 NOCACHE;

-- ── TEAM_SEQ (최대 team_id: 16) ──────────────────────────────
ALTER SEQUENCE TEAM_SEQ INCREMENT BY 16 NOCACHE;
SELECT TEAM_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE TEAM_SEQ INCREMENT BY 1 NOCACHE;

-- ── TEAM_MATCH_SEQ (최대 match_id: 8) ────────────────────────
ALTER SEQUENCE TEAM_MATCH_SEQ INCREMENT BY 8 NOCACHE;
SELECT TEAM_MATCH_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE TEAM_MATCH_SEQ INCREMENT BY 1 NOCACHE;

-- ── TEAM_MEMBER_SEQ (최대 team_member_id: 114) ───────────────
ALTER SEQUENCE TEAM_MEMBER_SEQ INCREMENT BY 114 NOCACHE;
SELECT TEAM_MEMBER_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE TEAM_MEMBER_SEQ INCREMENT BY 1 NOCACHE;

-- ── AUDITION_SEQ (최대 audition_id: 5) ───────────────────────
ALTER SEQUENCE AUDITION_SEQ INCREMENT BY 5 NOCACHE;
SELECT AUDITION_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE AUDITION_SEQ INCREMENT BY 1 NOCACHE;
